{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Requests and duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Percent of 200 per endpoint",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_requests_total{handler!=\"/metrics\", status=~\"2.*\"}) / sum by(handler) (http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "percent of 400 per endpoint",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{handler!~\"/metrics|none\", status=~\"4.*\"}) / sum by(handler) (requests_total{handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request duration per endpoint",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_request_duration_seconds_sum{handler!=\"/metrics\"} / http_request_duration_seconds_count{handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 200      over 10min",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_requests_total{job=\"megapi-log\", instance=\"megapi:8000\", status=\"2xx\", handler!=\"none\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 400 / 10m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_requests_total{instance=\"megapi:8000\", status=\"4xx\", handler!=\"none\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 500 / 10m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_requests_total{instance=\"megapi:8000\", status=\"5xx\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total{handler!~\"/metrics|none\", job=\"megapi-log\"}[5m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Total requests per 5m",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"megapi-log\"}[5m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "400 per endpoint / 5min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum by(handler) (increase(http_requests_total{job=\"megapi-log\", instance=\"megapi:8000\", status=\"4xx\", handler!=\"none\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"megapi-log\", instance=\"megapi:8000\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"megapi-log\", instance=\"megapi:8000\"}[5m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Total response in gigabytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (http_response_size_bytes_sum{job=\"megapi-log\"}/1073741824)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Count rows in table music_library",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(filepath) FROM music_library LIMIT 50 "
    }
   ]
  },
  {
   "title": "Count users in DB",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*) FROM users " }
   ]
  },
  {
   "title": "Count Users registered in past 7 days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_users_registered\nFROM users\nWHERE TO_TIMESTAMP(registered_at, 'YYYY-MM-DD HH24:MI:SS.US') >= NOW() - INTERVAL '7 days';\n"
    }
   ]
  },
  {
   "title": "Count User Uploaded Files",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM user_uploads"
    }
   ]
  },
  {
   "title": "Count unique users of model",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT user_id) AS unique_user_count\nFROM openl3_computation_log;\n"
    }
   ]
  },
  {
   "title": "Count extracted embeddings",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM openl3_computation_log LIMIT 50 "
    }
   ]
  },
  {
   "title": "Model's total average response time in ms",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(response_time_ms) FROM openl3_computation_log LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last 3 error messages from model",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT datetime, error_message\nFROM openl3_computation_log\nWHERE error_message IS NOT NULL\nLIMIT 3;\n"
    }
   ]
  },
  {
   "title": "WITH daily_data AS (",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH daily_data AS (\n  SELECT \n    datetime::date AS date,\n    COUNT(*) FILTER (WHERE response_time_ms > 0) AS count_with_response,\n    SUM(CASE WHEN response_time_ms > 0 THEN response_time_ms ELSE 0 END) / \n      COUNT(*) FILTER (WHERE response_time_ms > 0) AS avg_response_time\n  FROM openl3_computation_log\n  WHERE datetime >= CURRENT_DATE - INTERVAL '5 days'\n  GROUP BY DATE(datetime)\n),\nfinal_data AS (\n  SELECT \n    date,\n    CASE \n      WHEN count_with_response = 0 THEN NULL \n      ELSE avg_response_time \n    END AS avg_response_time\n  FROM daily_data\n)\nSELECT * FROM final_data\nORDER BY date DESC;\n"
    }
   ]
  },
  {
   "title": "number of times music-cnn has been used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/music_net/predict-genre/\", status=\"2xx\", instance=\"megapi:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of times music-cnn endpoint failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/music_net/predict-genre/\", status!=\"2xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model's last 7days response_time in ms",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 55 },
   "targets": [
    {
     "rawSql": "WITH daily_data AS (\n    SELECT \n        TO_CHAR(datetime, 'Day') AS day_name,\n        AVG(response_time_ms) AS avg_response_time_ms,\n        COUNT(*) AS count_logs\n    FROM \n        openl3_computation_log\n    WHERE \n        datetime >= CURRENT_DATE - INTERVAL '7 days'\n    GROUP BY \n        TO_CHAR(datetime, 'Day')\n),\nall_days AS (\n    SELECT \n        TO_CHAR(d.ts, 'Day') AS day_name,\n        d.row_num\n    FROM \n        generate_series(\n            CURRENT_DATE - INTERVAL '6 days',\n            CURRENT_DATE,\n            '1 day'::interval\n        ) WITH ORDINALITY AS d(ts, row_num)\n)\nSELECT \n    ad.day_name,\n    dd.avg_response_time_ms,\n    dd.count_logs,\n    CASE \n        WHEN ad.day_name = TO_CHAR(CURRENT_DATE, 'Day') THEN 'Today'\n        ELSE NULL\n    END AS day_type,\n    ad.row_num\nFROM \n    all_days ad\nLEFT JOIN \n    daily_data dd ON ad.day_name = dd.day_name\nORDER BY \n    ad.row_num;\n"
    },
    {}
   ]
  }
 ]
}