{
 "title": "FastAPI_POSTGRE_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "filenames in db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(filename) FROM music_library LIMIT 50 "
    }
   ]
  },
  {
   "title": "User Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*) FROM users " }
   ]
  },
  {
   "title": "Uploaded files count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM user_uploads"
    }
   ]
  }
 ]
}