services:

  mlflowdb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mlflowdb_data:/var/lib/mysql

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile-mlflow
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - NEW_USER_USERNAME=${NEW_USER_USERNAME}
      - NEW_USER_PASSWORD=${NEW_USER_PASSWORD}
    depends_on:
      - mlflowdb

  mlflow-setup:
    build:
      context: ./mlflow
      dockerfile: Dockerfile-setup-mlflow
    environment:
      - MLFLOW_TRACKIN_FULL_URL=${MLFLOW_TRACKIN_FULL_URL}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - NEW_USER_USERNAME=${NEW_USER_USERNAME}
      - NEW_USER_PASSWORD=${NEW_USER_PASSWORD}
    depends_on:
      - mlflow

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3030:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - LOCUST_FILE=locust_file.py
    volumes:
      - ./:/app
    working_dir: /app/locust

volumes:
  mlflowdb_data:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data: {}

networks:
  default: 
    name: global_network