FROM python:3.10-slim-buster

WORKDIR /mlflow/

RUN pip install mlflow

# Copy the Python script into the container
COPY setup_mlflow.py /mlflow/setup_mlflow.py

# Run the Python script
CMD ["python", "/mlflow/setup_mlflow.py"]